### ISSUE TITLE
More install issues

### ISSUE THREAD

**Issue by juan-pablo-vielma** [coin-or/Cbc.old#23]
Even with #11 there are still some install issues without svn. 

# Missing `--git`

Besides the `.sh` there is a missing `--git` in the Install instructions:

```bash
git clone --branch=stable/2.9 https://github.com/coin-or/Cbc Cbc-2.9
cd Cbc-2.9
git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
BuildTools/get.dependencies.sh fetch
```
yields 
```
Checkout ThirdParty/ASL
BuildTools/get.dependencies.sh: line 228: svn: command not found
```

# Data dependencies still use svn with `--git`

Running with `--git` still uses svn:

```bash
git clone --branch=stable/2.9 https://github.com/coin-or/Cbc Cbc-2.9
cd Cbc-2.9
git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
BuildTools/get.dependencies.sh fetch --git
```
yields 
```
Verify that there are no error message in the output above.
/home/jvielma/delme/Cbc-2.9
Checkout Data/Sample
BuildTools/get.dependencies.sh: line 271: svn: command not found
```

# Nested directories for some packages

After deleting lines 8-9 of `Dependencies` getting dependencies through
```bash
git clone --branch=stable/2.9 https://github.com/coin-or/Cbc Cbc-2.9
cd Cbc-2.9
git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
BuildTools/get.dependencies.sh fetch --git
```
works, but after that 
```bash
mkdir build
cd build
../configure
```
yields
```
checking for COIN-OR package CoinUtils... not given: No package 'coinutils' found
configure: error: Required package CoinUtils not available.
configure: error: /bin/bash '../../../Osi/Osi/configure' failed for Osi
configure: error: /bin/bash '../../Osi/configure' failed for Osi
```

The source of the problem seems to be that the github version of some packages have a nested structure that is not present in the svn versions (e.g. Osi directory inside of Osi directory). After eliminating this nested structure (e.g. with the script below) configure and make work (testing fails if the data dependencies are eliminated from `Dependencies` as described above. 
 
```bash
for i in {CoinUtils,Clp,Cgl,Osi}; do 
   mv $i ${i}.old; 
   mv ${i}.old/${i} $i; 
done
```

**Comment by tkralphs** [comment]
Thanks for the report @juan-pablo-vielma. For now, the script really assumes you have `svn`, which should be easy to install on any platform where you would have the ability to run a bash script from the command line. I do intend to remove the requirement for having `svn`, but it requires a non-trivial amount of additional work and I haven't found the time to do it. Is there a reason you don't want to or cannot have `svn` available? You will save yourself a lot of pain by just having it and if you only care about having the main code and not the dependent libraries checked out with git (which is probably the case), this is the easy fix.

When I implemented the script, I did check that the `--git` option was working. It should account for differences in the directory structure, etc. I made some additional bug fixes and enhancements in the `master` branch in the meantime, so could you try
```
git clone https://github.com/coin-or-tools/BuildTools
```
and see if that fixes it? If so, I will either change the documentation or else merge the changes over. If not, I have an idea what the problem could be and I'll check it in the next few days. It should be an easy fix.

Incidentally, do you have `pkg-config` installed? Installing that may also fix it and it should also be easy on any platform with `bash`.

**Comment by tkralphs** [comment]
By the way, if you could report further issues with the build script to http://www.github.com/coin-or-tools/BuildTools, that would be helpful.

**Comment by tkralphs** [comment]
I just tested and `--git` works fine if you use `get.dependencies.sh` from `master`. Could you test and see if it works for you?

**Comment by tkralphs** [comment]
Ah, I just looked more closely and realized that you are not using the `get.dependencies` script to do the building, just the fetching. After fetching, you need to do
```
BuildTools/get.dependencies.sh build
```
Monolithic builds in the old style are not going to be supported going forward and they won't work with a checkout by the build script (as you found out). 

The `get.dependencies` script is actually meant to replace the root `configure` script for the project, which currently only really serves to find dependencies. That root `configure` script will be going away soonish. Building with `get.dependencies` is more robust and getting rid of the root `configure` scripts will simplify lots of things in the build harness.

Perhaps the name of the script is a bit confusing. It started as a utility for fetching dependencies, but grew into something bigger.

**Comment by juan-pablo-vielma** [comment]
Some updates:
1. `BuildTools/get.dependencies.sh fetch --git` still fails in BuildTools master. Maybe it worked for you because you did have svn installed and the problematic code uses svn instead of git for the Data dependencies https://github.com/coin-or-tools/BuildTools/blob/f061d4713c0d3e2377d51f610a9911a635a16bd2/get.dependencies.sh#L350-L354  
2. After removing the data dependencies (manually because ` --skip=` didn't seem to work)
 fetch works and `BuildTools/get.dependencies.sh build` works on regular linux ...
3. but fails with `/opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lcoinblas` on a Docker image I am using for cross-compilation.  I think it is probably because of a known issue for this image with pkg-config (https://github.com/staticfloat/IpoptBuilder/blob/113cdf9462f14dd78c22d7fc36fff12e0f03b49f/build_tarballs.jl#L88-L92)

I opened an issue for 1 (coin-or-tools/BuildTools#3). in BuildTools. 3. is a bit esoteric and even if it is fixed I will still have problems cross-compiling ASL (ampl/mp#115) so I think it is safe to close this issue.
